# Find the linux audio device to use for audition. 
# At a linux terminal, do a "arecord -l". Then select the device (i.e. "card") number for the device you want to use.
alsadevnum: 0

# Signal sampling and framing parameters
frames_per_chunk: 512
sample_rate: 16000