# Find the linux audio device to use for audition. 
# At a linux terminal, do a "arecord -l". Then select the device (i.e. "card") number for the device you want to use.
alsadevnum: 1
n_channels: 1
channel_idx: 0
sample_rate: 16000
sample_fmt: 'S16LE'

# Signal sampling and framing parameters
frame_length: 800 # 50 ms
hop_length: 160 # 10 ms